### ISSUE TITLE
mpResources odd results

### ISSUE THREAD

**Issue by phil221** [sepiariver/mostpopular#4]
Hi YJ,

No matter how I format my call and regardless of how many resources I view, I run into two problems:
mpResources only ever returns two resources, regardless of clearing my session of cookies etc. and visiting other resources to try to see them listed as well.
The view count for these two resources never increments - always remains 1 for both resources listed. I’ve flushed caches and cleared session cookies before visiting these resource pages again to increase the view count, to no avail. mpResources call is as follows:

```
       [[mpResources?
            &tpl=`mpResourcesTpl`
        ]]
```

Very basic, as you can see. My mpResourcesTpl is as follows:

`<h1>Views for resource [[+pagetitle]] ([[+id]]): [[+views]]</h1>`

Is there a glaring error or omission that is skewing my results that you can see? Or if not, what troubleshooting steps would you recommend? Thanks for any time you can give this! MostPopular is an awesome extra and it is perfect for my use case, so I’m hoping very much that I can resolve these issues and make use of it.

**Comment by sepiariver** [comment]
What does your tracking snippet call look like please? (mpLogPageView)

**Comment by phil221** [comment]
Ah, of course that was it. Forgot to add it to the resource template. Working now, thanks for the reminder.
